### ISSUE TITLE
Caused by: java.lang.IllegalStateException: No DataSource set

### ISSUE THREAD

**Issue by wxydaydayup** [behappy-hospital/behappy-hospital#8]
您好，我是使用了windows自带的wsl连接的Ubuntu，我已经创建了nacos的sql表，但是nacos出现了没有连接数据库的报错，我觉得可能是nacos配置的问题，您能帮我看看怎么改吗？

nacos-server | Caused by: java.lang.IllegalStateException: No DataSource set
![image](https://user-images.githubusercontent.com/65120807/225275077-8f09a4ae-85b9-4c1a-8538-83a071d05a49.png)

我尝试过以下方法，但都没有奏效

一、更改过docker.compose.yml的 MYSQL_SERVICE_HOST的IP，

二、修改MYSQL_SERVICE_HOST=host.docker.interna

三、在MYSQL_SERVICE_DB_PARAM之后过加入了&serverTimezone=UTC

四、设置了mysql数据库权限可以对外访问,并且本机可以访问wsl2里面的mysql,但是nacos仍然显示No DataSource set

**Comment by wang-xiaowu** [comment]
发下你的docker-compose.yml文件，我看下

**Comment by wxydaydayup** [comment]
感谢！:rose: :rose: :rose:不过问题已经解决了。
说一下解决方案和注意的点！！！
1、需要注意JDK的版本 为 JDK17，可以自己百度怎么配置多个JDK的环境变量，太低版本的Idea无法使用JDK17，需要升级版本
2、端口号要改成 192.168.56.100，如果是wsl连接的话需要用脚本更改为静态IP，否则wsl的Ip每次都会变化。不更改静态IP的话除了要更改nacos里面的配置外，还有作者已经被打成jar里面的ip也要修改
由于每次重新启动 WSL2（指完全重新启动，即重新启动了 Windows 或者通过 `wsl --shutdown` 彻底停止 WSL2 后的首次启动，如果只是切出去的话那不需要）都需要执行一次，使用以下脚本就好：

保存成 `.cmd` 或者 `.bat` 文件，使用管理员身份运行即可。

```cmd
@echo off
setlocal enabledelayedexpansion

wsl -u root service docker start | findstr "Starting Docker" > nul
if !errorlevel! equ 0 (
    echo docker start success
    :: set wsl2 ip
    wsl -u root ip addr | findstr "192.168.56.100" > nul
    if !errorlevel! equ 0 (
        echo wsl ip has set
    ) else (
        wsl -u root ip addr add 192.168.56.100/28 broadcast 192.168.56.115 dev eth0 label eth0:1
        echo set wsl ip success: 192.168.56.100
    )
    
    :: set windows ip
    ipconfig | findstr "192.168.56.101" > nul
    if !errorlevel! equ 0 (
        echo windows ip has set
    ) else (
        netsh interface ip add address "vEthernet (WSL)" 192.168.56.101 255.255.255.240
        echo set windows ip success: 192.168.56.101
    )
)
pause
```

**Comment by wang-xiaowu** [comment]
1. jdk17需要idea起码是2021.2.1版本起
2. 如果不是使用我发的配置的话，需要将所有的`192.168.56.100`改为你当前环境的ip；可以不用配置wsl ip，使用你宿主机ip就好，我都配置了映射端口

你回答的很好，可以帮助到之后的人
